version: '3.7'

services:
  cloudleash:
      container_name: cloudleash
      image: pulumi/pulumi
      environment:
        PULUMI_ACCESS_TOKEN: ${PULUMI_ACCESS_TOKEN}
      volumes:
        - './:/stack'
        - '/var/run/docker.sock:/var/run/docker.sock'
      tty: true
